name: Build C Project

# Trigger the workflow on push to any branch
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    # Use the Docker container you specified to run the build
    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest # Change this if you're using a different Docker image source.
      options: --user vscode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker build -t BusinessTycoon .

      - name: Build project using tasks.json configuration
        run: |
          clang -fcolor-diagnostics -fansi-escape-codes -g \
          -I./include -I/usr/local/include ./src/*.c \
          -lncurses -o ./bin/main

      - name: Verify build
        run: ./bin/main

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: main-executable
          path: ./bin/main
